In [60]:
import pycaret
from matplotlib import pyplot as plt
import os
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
# visualization libraries
import seaborn as sns
from fbprophet import Prophet

In [61]:
median = pd.read_csv('medianSalesPrice.csv')

In [62]:
median= median.loc[median['CountyName'] == 'Miami-Dade County']
median=median.drop(columns=['RegionID','SizeRank','RegionName','RegionType','StateName','State','Metro'])

In [63]:
median = median.fillna(0)

In [64]:
null_columns=median.columns[median.isnull().any()]
median[null_columns].isnull().sum()

Series([], dtype: float64)

In [65]:
medianMelt= pd.melt(median, id_vars=['Bedrooms', 'City', 'CountyName'])

In [66]:
medianMelt.rename(columns = {'variable': 'date'}, inplace = True)

In [67]:
medianMelt['date']=pd.to_datetime(medianMelt['date'])

In [68]:
medianMelt.head()

   Bedrooms                     City         CountyName       date     value
0         1        Sunny Isles Beach  Miami-Dade County 2015-01-31  172691.0
1         1              Miami Beach  Miami-Dade County 2015-01-31  264769.0
2         1            The Crossings  Miami-Dade County 2015-01-31  110740.0
3         1                  Hialeah  Miami-Dade County 2015-01-31   85328.0
4         1  Village of Palmetto Bay  Miami-Dade County 2015-01-31  111744.0

In [69]:
# medianMelt2=medianMelt.drop(columns=['CountyName','date'])
medianMelt2=medianMelt.drop(columns=['CountyName'])

In [70]:
medianMelt2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27375 entries, 0 to 27374
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Bedrooms  27375 non-null  int64
 1   City      27375 non-null  object
 2   date      27375 non-null  datetime64[ns]
 3   value     27375 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 855.6+ KB

In [71]:
from pycaret.classification import setup
from pycaret.classification import tune_model
from pycaret.classification import compare_models, create_model,plot_model, predict_model

In [72]:
medianMelt2 = medianMelt2.loc[medianMelt2['date'] >= '2020-01-31']

In [78]:
medianMelt2 = medianMelt2.loc[medianMelt2['City'] == 'Miami']

In [79]:
medianMelt2

      Bedrooms   City      value
10           1  Miami   135137.0
11           1  Miami   169014.0
13           1  Miami   264488.0
15           1  Miami   140743.0
23           1  Miami   290401.0
...        ...    ...        ...
4849         5  Miami   436298.0
4850         5  Miami   340303.0
4852         5  Miami   503530.0
4858         5  Miami  1521114.0
4862         5  Miami   726119.0

[1131 rows x 3 columns]

In [80]:
medianMelt2=medianMelt2[['Bedrooms','City','value']]

In [81]:
medianMelt2=medianMelt2.reset_index(drop=True)
medianMelt2

      Bedrooms   City      value
0            1  Miami   135137.0
1            1  Miami   169014.0
2            1  Miami   264488.0
3            1  Miami   140743.0
4            1  Miami   290401.0
...        ...    ...        ...
1126         5  Miami   436298.0
1127         5  Miami   340303.0
1128         5  Miami   503530.0
1129         5  Miami  1521114.0
1130         5  Miami   726119.0

[1131 rows x 3 columns]

In [82]:
medianMelt2['City'].value_counts()

Miami    1131
Name: City, dtype: int64

In [83]:
grid = setup(data=medianMelt2, target=medianMelt2.columns[-1], html=True, silent=False, verbose=True) #

In [84]:
medianMelt2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1131 entries, 0 to 1130
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Bedrooms  1131 non-null   int64
 1   City      1131 non-null   object
 2   value     1131 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 26.6+ KB

In [91]:
len(medianMelt2)

1131

In [41]:
# clf1 = setup(data = medianMelt2, 
#              target = 'value',
#              numeric_imputation = 'mean',
#              #categorical_features = ['Bedrooms'], 
#              #ignore_features = ['City', 'Bedrooms'],
#              silent = True)

In [88]:
grid

(877      144689.0
 57       360765.0
 899      301151.0
 1069     236486.0
 672      819409.0
           ...
 1123    2160489.0
 539      154447.0
 1001     721324.0
 178      291713.0
 400      238074.0
 Name: value, Length: 791, dtype: float32,
 False,
 'value',
 'clf-default-name',
 StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
       Bedrooms_1  Bedrooms_2  Bedrooms_3  Bedrooms_4  Bedrooms_5  City_Miami
 591          0.0         0.0         0.0         1.0         0.0         1.0
 79           0.0         0.0         0.0         0.0         1.0         1.0
 119          0.0         1.0         0.0         0.0         0.0         1.0
 298          0.0         0.0         1.0         0.0         0.0         1.0
 66           0.0         0.0         0.0         1.0         0.0         1.0
 ...          ...         ...         ...         ...         ...         ...
 775          0.0         0.0         0.0         0.0         1.0         1.0
 714          0.0         1.0         0.0         0.0         0.0         1.0
 1034         0.0         0.0         0.0         0.0         1.0         1.0
 575          0.0         0.0         1.0         0.0         0.0         1.0
 621          1.0         0.0         0.0         0.0         0.0         1.0

 [340 rows x 6 columns],
       Bedrooms   City      value
 0            1  Miami   135137.0
 1            1  Miami   169014.0
 2            1  Miami   264488.0
 3            1  Miami   140743.0
 4            1  Miami   290401.0
 ...        ...    ...        ...
 1126         5  Miami   436298.0
 1127         5  Miami   340303.0
 1128         5  Miami   503530.0
 1129         5  Miami  1521114.0
 1130         5  Miami   726119.0

 [1131 rows x 3 columns],
 5,
 'lightgbm',
       Bedrooms_1  Bedrooms_2  Bedrooms_3  Bedrooms_4  Bedrooms_5  City_Miami
 0            1.0         0.0         0.0         0.0         0.0         1.0
 1            1.0         0.0         0.0         0.0         0.0         1.0
 2            1.0         0.0         0.0         0.0         0.0         1.0
 3            1.0         0.0         0.0         0.0         0.0         1.0
 4            1.0         0.0         0.0         0.0         0.0         1.0
 ...          ...         ...         ...         ...         ...         ...
 1126         0.0         0.0         0.0         0.0         1.0         1.0
 1127         0.0         0.0         0.0         0.0         1.0         1.0
 1128         0.0         0.0         0.0         0.0         1.0         1.0
 1129         0.0         0.0         0.0         0.0         1.0         1.0
 1130         0.0         0.0         0.0         0.0         1.0         1.0

 [1131 rows x 6 columns],
 'box-cox',
 None,
 '7d28',
 {'acc': <pycaret.containers.metrics.classification.AccuracyMetricContainer at 0x2a2b1d29948>,
  'auc': <pycaret.containers.metrics.classification.ROCAUCMetricContainer at 0x2a2b1d20608>,
  'recall': <pycaret.containers.metrics.classification.RecallMetricContainer at 0x2a2b1d20348>,
  'precision': <pycaret.containers.metrics.classification.PrecisionMetricContainer at 0x2a2b4230808>,
  'f1': <pycaret.containers.metrics.classification.F1MetricContainer at 0x2a2b40dfa48>,
  'kappa': <pycaret.containers.metrics.classification.KappaMetricContainer at 0x2a2b40dfd88>,
  'mcc': <pycaret.containers.metrics.classification.MCCMetricContainer at 0x2a2b40df948>},
 False,
 -1,
 0        135137.0
 1        169014.0
 2        264488.0
 3        140743.0
 4        290401.0
           ...
 1126     436298.0
 1127     340303.0
 1128     503530.0
 1129    1521114.0
 1130     726119.0
 Name: value, Length: 1131, dtype: float32,
 {'parameter': 'Hyperparameters',
  'auc': 'AUC',
  'confusion_matrix': 'Confusion Matrix',
  'threshold': 'Threshold',
  'pr': 'Precision Recall',
  'error': 'Prediction Error',
  'class_report': 'Class Report',
  'rfe': 'Feature Selection',
  'learning': 'Learning Curve',
  'manifold': 'Manifold Learning',
  'calibration': 'Calibration Curve',
  'vc': 'Validation Curve',
  'dimension': 'Dimensions',
  'feature': 'Feature Importance',
  'feature_all': 'Feature Importance (All)',
  'boundary': 'Decision Boundary',
  'lift': 'Lift Chart',
  'gain': 'Gain Chart',
  'tree': 'Decision Tree'},
 10,
 False,
 [],
 None,
 {'lr': <pycaret.containers.models.classification.LogisticRegressionClassifierContainer at 0x2a2b1cf2d08>,
  'knn': <pycaret.containers.models.classification.KNeighborsClassifierContainer at 0x2a2b1cf23c8>,
  'nb': <pycaret.containers.models.classification.GaussianNBClassifierContainer at 0x2a2b1cf2708>,
  'dt': <pycaret.containers.models.classification.DecisionTreeClassifierContainer at 0x2a2b1cf2808>,
  'svm': <pycaret.containers.models.classification.SGDClassifierContainer at 0x2a2b1cf40c8>,
  'rbfsvm': <pycaret.containers.models.classification.SVCClassifierContainer at 0x2a2b1cf47c8>,
  'gpc': <pycaret.containers.models.classification.GaussianProcessClassifierContainer at 0x2a2b1cf4148>,
  'mlp': <pycaret.containers.models.classification.MLPClassifierContainer at 0x2a2b1cf4a88>,
  'ridge': <pycaret.containers.models.classification.RidgeClassifierContainer at 0x2a2b1cf4fc8>,
  'rf': <pycaret.containers.models.classification.RandomForestClassifierContainer at 0x2a2b1cf2548>,
  'qda': <pycaret.containers.models.classification.QuadraticDiscriminantAnalysisContainer at 0x2a2b1cf2688>,
  'ada': <pycaret.containers.models.classification.AdaBoostClassifierContainer at 0x2a2b1cf58c8>,
  'gbc': <pycaret.containers.models.classification.GradientBoostingClassifierContainer at 0x2a2b1cf4108>,
  'lda': <pycaret.containers.models.classification.LinearDiscriminantAnalysisContainer at 0x2a2b1cf43c8>,
  'et': <pycaret.containers.models.classification.ExtraTreesClassifierContainer at 0x2a2b1cf56c8>,
  'lightgbm': <pycaret.containers.models.classification.LGBMClassifierContainer at 0x2a2b1cff3c8>},
 <MLUsecase.CLASSIFICATION: 1>,
 -1,
 [('Setup Config',
                                  Description             Value
   0                               session_id              8709
   1                                   Target             value
   2                              Target Type        Multiclass
   3                            Label Encoded              None
   4                            Original Data         (1131, 3)
   5                           Missing Values             False
   6                         Numeric Features                 0
   7                     Categorical Features                 2
   8                         Ordinal Features             False
   9                High Cardinality Features             False
   10                 High Cardinality Method              None
   11                   Transformed Train Set          (791, 6)
   12                    Transformed Test Set          (340, 6)
   13                      Shuffle Train-Test              True
   14                     Stratify Train-Test             False
   15                          Fold Generator   StratifiedKFold
   16                             Fold Number                10
   17                                CPU Jobs                -1
   18                                 Use GPU             False
   19                          Log Experiment             False
   20                         Experiment Name  clf-default-name
   21                                     USI              7d28
   22                         Imputation Type            simple
   23          Iterative Imputation Iteration              None
   24                         Numeric Imputer              mean
   25      Iterative Imputation Numeric Model              None
   26                     Categorical Imputer          constant
   27  Iterative Imputation Categorical Model              None
   28           Unknown Categoricals Handling    least_frequent
   29                               Normalize             False
   30                        Normalize Method              None
   31                          Transformation             False
   32                   Transformation Method              None
   33                                     PCA             False
   34                              PCA Method              None
   35                          PCA Components              None
   36                     Ignore Low Variance             False
   37                     Combine Rare Levels             False
   38                    Rare Level Threshold              None
   39                         Numeric Binning             False
   40                         Remove Outliers             False
   41                      Outliers Threshold              None
   42                Remove Multicollinearity             False
   43             Multicollinearity Threshold              None
   44                              Clustering             False
   45                    Clustering Iteration              None
   46                     Polynomial Features             False
   47                       Polynomial Degree              None
   48                    Trignometry Features             False
   49                    Polynomial Threshold              None
   50                          Group Features             False
   51                       Feature Selection             False
   52                Feature Selection Method           classic
   53            Features Selection Threshold              None
   54                     Feature Interaction             False
   55                           Feature Ratio             False
   56                   Interaction Threshold              None
   57                           Fix Imbalance             False
   58                    Fix Imbalance Method             SMOTE),
  ('X_training Set',
         Bedrooms_1  Bedrooms_2  Bedrooms_3  Bedrooms_4  Bedrooms_5  City_Miami
   877          1.0         0.0         0.0         0.0         0.0         1.0
   57           0.0         0.0         0.0         1.0         0.0         1.0
   899          0.0         1.0         0.0         0.0         0.0         1.0
   1069         0.0         1.0         0.0         0.0         0.0         1.0
   672          0.0         0.0         0.0         1.0         0.0         1.0
   ...          ...         ...         ...         ...         ...         ...
   1123         0.0         0.0         0.0         0.0         1.0         1.0
   539          1.0         0.0         0.0         0.0         0.0         1.0
   1001         0.0         0.0         1.0         0.0         0.0         1.0
   178          1.0         0.0         0.0         0.0         0.0         1.0
   400          0.0         0.0         1.0         0.0         0.0         1.0

   [791 rows x 6 columns]),
  ('y_training Set',
   877      144689.0
   57       360765.0
   899      301151.0
   1069     236486.0
   672      819409.0
             ...
   1123    2160489.0
   539      154447.0
   1001     721324.0
   178      291713.0
   400      238074.0
   Name: value, Length: 791, dtype: float32),
  ('X_test Set',
         Bedrooms_1  Bedrooms_2  Bedrooms_3  Bedrooms_4  Bedrooms_5  City_Miami
   591          0.0         0.0         0.0         1.0         0.0         1.0
   79           0.0         0.0         0.0         0.0         1.0         1.0
   119          0.0         1.0         0.0         0.0         0.0         1.0
   298          0.0         0.0         1.0         0.0         0.0         1.0
   66           0.0         0.0         0.0         1.0         0.0         1.0
   ...          ...         ...         ...         ...         ...         ...
   775          0.0         0.0         0.0         0.0         1.0         1.0
   714          0.0         1.0         0.0         0.0         0.0         1.0
   1034         0.0         0.0         0.0         0.0         1.0         1.0
   575          0.0         0.0         1.0         0.0         0.0         1.0
   621          1.0         0.0         0.0         0.0         0.0         1.0

   [340 rows x 6 columns]),
  ('y_test Set',
   591      233145.0
   79      2158600.0
   119      447952.0
   298      247922.0
   66       266298.0
             ...
   775     2113173.0
   714      259006.0
   1034    2228186.0
   575      328382.0
   621      131682.0
   Name: value, Length: 340, dtype: float32),
  ('Transformation Pipeline',
   Pipeline(memory=None,
            steps=[('dtypes',
                    DataTypes_Auto_infer(categorical_features=[],
                                         display_types=True, features_todrop=[],
                                         id_columns=[],
                                         ml_usecase='classification',
                                         numerical_features=[], target='value',
                                         time_features=[])),
                   ('imputer',
                    Simple_Imputer(categorical_strategy='not_available',
                                   fill_value_categorical=None,
                                   fill_value_numerical=None,
                                   numeric_strate...
                   ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                   ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                   ('cluster_all', 'passthrough'),
                   ('dummy', Dummify(target='value')),
                   ('fix_perfect', Remove_100(target='value')),
                   ('clean_names', Clean_Colum_Names()),
                   ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                   ('dfs', 'passthrough'), ('pca', 'passthrough')],
            verbose=False))],
 False,
 8709,
 Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False),
 Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='value',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strate...
                 ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                 ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                 ('cluster_all', 'passthrough'),
                 ('dummy', Dummify(target='value')),
                 ('fix_perfect', Remove_100(target='value')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough')],
          verbose=False),
 False,
 [<pandas.io.formats.style.Styler at 0x2a2b1cf29c8>,
  Empty DataFrame
  Columns: []
  Index: [],
  Empty DataFrame
  Columns: []
  Index: [],
  Empty DataFrame
  Columns: []
  Index: []],
 [],
 {'USI',
  'X',
  'X_test',
  'X_train',
  '_all_metrics',
  '_all_models',
  '_all_models_internal',
  '_available_plots',
  '_gpu_n_jobs_param',
  '_internal_pipeline',
  '_ml_usecase',
  'create_model_container',
  'data_before_preprocess',
  'display_container',
  'exp_name_log',
  'experiment__',
  'fix_imbalance_method_param',
  'fix_imbalance_param',
  'fold_generator',
  'fold_groups_param',
  'fold_param',
  'fold_shuffle_param',
  'gpu_param',
  'html_param',
  'imputation_classifier',
  'imputation_regressor',
  'iterative_imputation_iters_param',
  'log_plots_param',
  'logging_param',
  'master_model_container',
  'n_jobs_param',
  'prep_pipe',
  'pycaret_globals',
  'seed',
  'stratify_param',
  'target_param',
  'transform_target_method_param',
  'transform_target_param',
  'y',
  'y_test',
  'y_train'},
 591      233145.0
 79      2158600.0
 119      447952.0
 298      247922.0
 66       266298.0
           ...
 775     2113173.0
 714      259006.0
 1034    2228186.0
 575      328382.0
 621      131682.0
 Name: value, Length: 340, dtype: float32,
       Bedrooms_1  Bedrooms_2  Bedrooms_3  Bedrooms_4  Bedrooms_5  City_Miami
 877          1.0         0.0         0.0         0.0         0.0         1.0
 57           0.0         0.0         0.0         1.0         0.0         1.0
 899          0.0         1.0         0.0         0.0         0.0         1.0
 1069         0.0         1.0         0.0         0.0         0.0         1.0
 672          0.0         0.0         0.0         1.0         0.0         1.0
 ...          ...         ...         ...         ...         ...         ...
 1123         0.0         0.0         0.0         0.0         1.0         1.0
 539          1.0         0.0         0.0         0.0         0.0         1.0
 1001         0.0         0.0         1.0         0.0         0.0         1.0
 178          1.0         0.0         0.0         0.0         0.0         1.0
 400          0.0         0.0         1.0         0.0         0.0         1.0

 [791 rows x 6 columns],
 True,
 'lightgbm',
 False,
 {'lr': <pycaret.containers.models.classification.LogisticRegressionClassifierContainer at 0x2a2b1cf2bc8>,
  'knn': <pycaret.containers.models.classification.KNeighborsClassifierContainer at 0x2a2b1cffe48>,
  'nb': <pycaret.containers.models.classification.GaussianNBClassifierContainer at 0x2a2b1d00048>,
  'dt': <pycaret.containers.models.classification.DecisionTreeClassifierContainer at 0x2a2b1d00108>,
  'svm': <pycaret.containers.models.classification.SGDClassifierContainer at 0x2a2b1d00588>,
  'rbfsvm': <pycaret.containers.models.classification.SVCClassifierContainer at 0x2a2b1d00a88>,
  'gpc': <pycaret.containers.models.classification.GaussianProcessClassifierContainer at 0x2a2b1d00608>,
  'mlp': <pycaret.containers.models.classification.MLPClassifierContainer at 0x2a2b1d00cc8>,
  'ridge': <pycaret.containers.models.classification.RidgeClassifierContainer at 0x2a2b1d1d288>,
  'rf': <pycaret.containers.models.classification.RandomForestClassifierContainer at 0x2a2b1d00188>,
  'qda': <pycaret.containers.models.classification.QuadraticDiscriminantAnalysisContainer at 0x2a2b1cff588>,
  'ada': <pycaret.containers.models.classification.AdaBoostClassifierContainer at 0x2a2b1d1dec8>,
  'gbc': <pycaret.containers.models.classification.GradientBoostingClassifierContainer at 0x2a2b1d005c8>,
  'lda': <pycaret.containers.models.classification.LinearDiscriminantAnalysisContainer at 0x2a2b1d1da08>,
  'et': <pycaret.containers.models.classification.ExtraTreesClassifierContainer at 0x2a2b1d29b48>,
  'lightgbm': <pycaret.containers.models.classification.LGBMClassifierContainer at 0x2a2b1d29b08>,
  'Bagging': <pycaret.containers.models.classification.BaggingClassifierContainer at 0x2a2b1d29908>,
  'Stacking': <pycaret.containers.models.classification.StackingClassifierContainer at 0x2a2b1d1d688>,
  'Voting': <pycaret.containers.models.classification.VotingClassifierContainer at 0x2a2b1d29888>,
  'CalibratedCV': <pycaret.containers.models.classification.CalibratedClassifierCVContainer at 0x2a2b1d29bc8>},
 False)

In [87]:
compare_models(include=['lr','nb'])

[]

In [85]:
compare_models(n_select=2)

[]

In [26]:
import os

In [27]:
os.environ

environ{'ACLOCAL_PATH': 'C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal',
        'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\betan\\AppData\\Roaming',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'DESKTOP-N71JR62',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'CONDA_DEFAULT_ENV': 'PythonTime',
        'CONDA_EXE': 'C:/users/betan/anaconda3/Scripts/conda.exe',
        'CONDA_PREFIX': 'C:\\users\\betan\\anaconda3\\envs\\PythonTime',
        'CONDA_PROMPT_MODIFIER': '(PythonTime) ',
        'CONDA_PYTHON_EXE': 'C:/users/betan/anaconda3/python.exe',
        'CONDA_SHLVL': '1',
        'CONFIG_SITE': 'C:/Program Files/Git/mingw64/etc/config.site',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'DISPLAY': 'needs-to-be-defined',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'EXEPATH': 'C:\\Program Files\\Git',
        'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
        'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
        'HOME': 'C:\\Users\\betan',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\betan',
        'HOSTNAME': 'DESKTOP-N71JR62',
        'INFOPATH': 'C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info',
        'LANG': 'en_US.UTF-8',
        'LOCALAPPDATA': 'C:\\Users\\betan\\AppData\\Local',
        'LOGONSERVER': '\\\\DESKTOP-N71JR62',
        'MANPATH': 'C:\\Program Files\\Git\\mingw64\\local\\man;C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man',
        'MINGW_CHOST': 'x86_64-w64-mingw32',
        'MINGW_PACKAGE_PREFIX': 'mingw-w64-x86_64',
        'MINGW_PREFIX': 'C:/Program Files/Git/mingw64',
        'MSYSTEM': 'MINGW64',
        'MSYSTEM_CARCH': 'x86_64',
        'MSYSTEM_CHOST': 'x86_64-w64-mingw32',
        'MSYSTEM_PREFIX': 'C:/Program Files/Git/mingw64',
        'NUMBER_OF_PROCESSORS': '12',
        'ORIGINAL_PATH': 'C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\betan\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Git\\cmd;C:\\Users\\betan\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\betan\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\MongoDB\\Server\\4.4\\bin;C:\\Program Files\\heroku\\bin',
        'ORIGINAL_TEMP': 'C:/Users/betan/AppData/Local/Temp',
        'ORIGINAL_TMP': 'C:/Users/betan/AppData/Local/Temp',
        'OS': 'Windows_NT',
        'ONEDRIVE': 'C:\\Users\\betan\\OneDrive',
        'ONEDRIVECONSUMER': 'C:\\Users\\betan\\OneDrive',
        'PATH': 'C:\\users\\betan\\anaconda3\\envs\\PythonTime;C:\\users\\betan\\anaconda3\\envs\\PythonTime\\Library\\mingw-w64\\bin;C:\\users\\betan\\anaconda3\\envs\\PythonTime\\Library\\usr\\bin;C:\\users\\betan\\anaconda3\\envs\\PythonTime\\Library\\bin;C:\\users\\betan\\anaconda3\\envs\\PythonTime\\Scripts;C:\\users\\betan\\anaconda3\\envs\\PythonTime\\bin;C;C:\\Program Files\\Git\\users\\betan\\anaconda3;C;C:\\Program Files\\Git\\users\\betan\\anaconda3\\Library\\mingw-w64\\bin;C;C:\\Program Files\\Git\\users\\betan\\anaconda3\\Library\\usr\\bin;C;C:\\Program Files\\Git\\users\\betan\\anaconda3\\Library\\bin;C;C:\\Program Files\\Git\\users\\betan\\anaconda3\\Scripts;C;C:\\Program Files\\Git\\users\\betan\\anaconda3\\bin;C;C:\\Program Files\\Git\\users\\betan\\anaconda3\\Scripts\\condabin;C:\\Program Files\\R\\R-4.0.3\\bin\\x64;C:\\sqlite;C:\\users\\betan\\Anaconda3;C:\\users\\betan\\anaconda3\\scripts;C:\\Program Files\\PostgreSQL\\11\\bin;C:\\Program Files\\MongoDB\\Server\\4.0\\bin;C:\\Users\\betan\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\betan\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Git\\cmd;C:\\Users\\betan\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\betan\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\MongoDB\\Server\\4.4\\bin;C:\\Program Files\\heroku\\bin;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl;C:\\users\\betan\\anaconda3\\envs\\PythonTime\\lib\\site-packages\\llvmlite\\binding',
        'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
        'PKG_CONFIG_PATH': 'C:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;C:\\Program Files\\Git\\mingw64\\share\\pkgconfig',
        'PLINK_PROTOCOL': 'ssh',
        'PROCESSOR_ARCHITECTURE': 'AMD64',
        'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel',
        'PROCESSOR_LEVEL': '6',
        'PROCESSOR_REVISION': '9e0a',
        'PROGRAMFILES': 'C:\\Program Files',
        'PROMPT': '$P$G',
        'PS1': '(PythonTime) \\[\\033]0;$TITLEPREFIX:$PWD\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ',
        'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
        'PUBLIC': 'C:\\Users\\Public',
        'PWD': 'C:/Users/betan/Documents/Martin/Bootcamp',
        'PROGRAMDATA': 'C:\\ProgramData',
        'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
        'PROGRAMW6432': 'C:\\Program Files',
        'SESSIONNAME': 'Console',
        'SHELL': 'C:\\Program Files\\Git\\usr\\bin\\bash.exe',
        'SHLVL': '1',
        'SQLPASS': '12345',
        'SSH_ASKPASS': 'C:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass',
        'SYSTEMDRIVE': 'C:',
        'SYSTEMROOT': 'C:\\WINDOWS',
        'TEMP': 'C:\\Users\\betan\\AppData\\Local\\Temp',
        'TERM': 'xterm-color',
        'TMP': 'C:\\Users\\betan\\AppData\\Local\\Temp',
        'TMPDIR': 'C:\\Users\\betan\\AppData\\Local\\Temp',
        'USERDOMAIN': 'DESKTOP-N71JR62',
        'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-N71JR62',
        'USERNAME': 'betan',
        'USERPROFILE': 'C:\\Users\\betan',
        'WINDIR': 'C:\\WINDOWS',
        '_': 'C:/users/betan/anaconda3/envs/PythonTime/Scripts/jupyter',
        '_CE_CONDA': '',
        '_CE_M': '',
        'JPY_INTERRUPT_EVENT': '2172',
        'IPY_INTERRUPT_EVENT': '2172',
        'JPY_PARENT_PID': '2176',
        'CLICOLOR': '1',
        'PAGER': 'cat',
        'GIT_PAGER': 'cat',
        'MPLBACKEND': 'module://ipykernel.pylab.backend_inline',
        'KMP_DUPLICATE_LIB_OK': 'True',
        'KMP_INIT_AT_FORK': 'FALSE'}

In [28]:
!which python

/c/users/betan/anaconda3/envs/PythonTime/python

In [29]:
!python --version

Python 3.7.9